/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Form.FormBarang;
import Form.FormLogin;
import Form.FromTransaksi;
import Form.Laporan;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author WhoAmI
 */
public class MenuBar extends javax.swing.JFrame {
    
    public static void main(String[] args) {
        MenuBar menu = new MenuBar();
        menu.show();
        
    }
    /**
     * Creates new form MenuBar
     */
    public MenuBar() {
       
        initComponents();
        
    }
    public void loginActive(boolean item, boolean master, boolean laporan, boolean transaksi){
        menuLogin.setEnabled(item); 
        Jmaster.setEnabled(master);
        JLaporan.setEnabled(laporan);
        Jtransaksi.setEnabled(transaksi);
    }
    public void loginDisabled(){
        logOut.setEnabled(false);
    }
   
    
   
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Jmaster = new javax.swing.JMenu();
        JdtBarang = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        logOut = new javax.swing.JMenuItem();
        Jtransaksi = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        Pembelian = new javax.swing.JMenuItem();
        JLaporan = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Putri Syafarinda\\Downloads\\WhatsApp Image 2020-05-16 at 06.58.00.jpeg")); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 255));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(200, 50));

        Jmaster.setBackground(new java.awt.Color(255, 255, 255));
        Jmaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16-16-1b751226558e77b2a304882fe19bbdde.png"))); // NOI18N
        Jmaster.setText("TOKO VIA");

        JdtBarang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        JdtBarang.setBackground(new java.awt.Color(255, 102, 153));
        JdtBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/16-16-6a4d92524f0c1c9af37145456fc98070-Add.png"))); // NOI18N
        JdtBarang.setText("Data Barang");
        JdtBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JdtBarangActionPerformed(evt);
            }
        });
        Jmaster.add(JdtBarang);

        jMenuBar1.add(Jmaster);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/setting.png"))); // NOI18N
        jMenu2.setText("Pengaturan Akun");

        menuLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        menuLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/avatar (1).png"))); // NOI18N
        menuLogin.setText("Login");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        jMenu2.add(menuLogin);

        logOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/web.png"))); // NOI18N
        logOut.setText("LogOut");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        jMenu2.add(logOut);

        jMenuBar1.add(jMenu2);

        Jtransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Shop-icon.png"))); // NOI18N
        Jtransaksi.setText("Transaksi");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cart-icon.png"))); // NOI18N
        jMenuItem2.setText("Penjualan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Jtransaksi.add(jMenuItem2);

        Pembelian.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        Pembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cart-add-icon.png"))); // NOI18N
        Pembelian.setText("Pembelian");
        Pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PembelianActionPerformed(evt);
            }
        });
        Jtransaksi.add(Pembelian);

        jMenuBar1.add(Jtransaksi);

        JLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/folder-icon.png"))); // NOI18N
        JLaporan.setText("Laporan");
        JLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLaporanMouseClicked(evt);
            }
        });

        jMenuItem1.setText("Data Barang");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        JLaporan.add(jMenuItem1);

        jMenuBar1.add(JLaporan);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        jMenu3.setText("Keluar ");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenu3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu3KeyPressed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed

        int opsi = JOptionPane.showConfirmDialog(null, "Benarkah Anda Akan Keluar Akun ?", 
                "Keluar Akun", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (opsi == JOptionPane.YES_OPTION){ 
                logOut.setEnabled(false);
                menuLogin.setEnabled(true);
                JdtBarang.setEnabled(false);
                Jtransaksi.setEnabled(false);
                Jmaster.setEnabled(false);
                JLaporan.setEnabled(false);
        } else{
           
    }
    }//GEN-LAST:event_logOutActionPerformed

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
           Form.FormLogin login = new FormLogin();
           login.setVisible(true);
           dispose();
    }//GEN-LAST:event_menuLoginActionPerformed
  
    private void jMenu3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu3KeyPressed

    }//GEN-LAST:event_jMenu3KeyPressed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void PembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PembelianActionPerformed
        Form.FormBarang FormBarang = new FormBarang();
        FormBarang.setLocationRelativeTo(null);
        FormBarang.setVisible(true);
    }//GEN-LAST:event_PembelianActionPerformed

    private void JLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLaporanMouseClicked

    }//GEN-LAST:event_JLaporanMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
      int selectedOption = JOptionPane.showConfirmDialog(null,
            "Apakah anda akan menutup system?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Laporan lprn = new Laporan();
        lprn.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Form.FromTransaksi FromTransaksi = new FromTransaksi();
        FromTransaksi.setLocationRelativeTo(null);
        FromTransaksi.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void JdtBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JdtBarangActionPerformed

    }//GEN-LAST:event_JdtBarangActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JLaporan;
    private javax.swing.JMenuItem JdtBarang;
    private javax.swing.JMenu Jmaster;
    private javax.swing.JMenu Jtransaksi;
    private javax.swing.JMenuItem Pembelian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem logOut;
    private javax.swing.JMenuItem menuLogin;
    // End of variables declaration//GEN-END:variables

}
